### ISSUE TITLE
Highradius Source Code Data Leakage | Action Needed ASAP

### ISSUE THREAD

**Issue by Ranjit-Chigurupati** [abhishek000yadav/HighRadius1#1]
Hi abhishek000yadav,

We identified that one of your GitHub public Repositories “HighRadius1” contains a source code which is related/owned by the Highradius. Please Delete/remove the respective data from the public exposure, if not this will be considered as a Copyright Violation and necessary action will be taken.

Any data that is related/owned by the Highradius Corporation should not be used for your personal benefits or should not exposed in to the public. Any such unauthorized activities will be considered as series offence and necessary legal actions will be taken.

Thanks & Regards,
Ranjit Kumar Chigurupati,
Led Information Security Engineer,
Highradius Corporation.

**Comment by abhishek000yadav** [comment]
Hi there,
Can you please mention the exact details of the source code which belongs
to highradius .It was actually a web project that every tech intern had to
do and and I didn’t use any  highradius framework in the project . If any i
would be happy to rectify or remove ,please mention the source code details.

Thank you.
Abhishek Vardhan

**Comment by Ranjit-Chigurupati** [comment]
+Naresh Goud ***@***.***>

On Fri, Sep 30, 2022 at 4:50 PM Abhishek Vardhan ***@***.***>
wrote:

> Hi there,
> Can you please mention the exact details of the source code which belongs
> to highradius .It was actually a web project that every tech intern had to
> do and and I didn’t use any highradius framework in the project . If any i
> would be happy to rectify or remove ,please mention the source code
> details.
>
> Thank you.
> Abhishek Vardhan
>
> On Fri, 30 Sep 2022 at 12:33 PM, Ranjit-Chigurupati <
> ***@***.***> wrote:
>
> > Hi abhishek000yadav,
> >
> > We identified that one of your GitHub public Repositories “HighRadius1”
> > contains a source code which is related/owned by the Highradius. Please
> > Delete/remove the respective data from the public exposure, if not this
> > will be considered as a Copyright Violation and necessary action will be
> > taken.
> >
> > Any data that is related/owned by the Highradius Corporation should not
> be
> > used for your personal benefits or should not exposed in to the public.
> Any
> > such unauthorized activities will be considered as series offence and
> > necessary legal actions will be taken.
> >
> > Thanks & Regards,
> > Ranjit Kumar Chigurupati,
> > Led Information Security Engineer,
> > Highradius Corporation.
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38EV0gzJRrfk3hb1n3baLjnAps2YoKFnKIRJWm7CYkRcJLeM5-2BzMZxh5o7QjlzPCbLH0c6SrKThVH61uLpj1UUTY-3D2oe1_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyotOYWK-2F0IFHnWW-2BRBfGKdwZvrwHvzjDqRKTh6Ihm8xhrVwGFm60M8bhefF6Wm-2BvRcfR1WotcRCVkFsGlexBwCycj6gra3-2BIJ1g8WVCrEtHJ8rpU0bSQOFPrKzQ0Ynk6TaE21-2Fn2yvDuJI1mmS89zf1-2FO8uD0bGAQxpLSdAzOV4Jpg-3D-3D>, or
> unsubscribe
> > <
> https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38OLpao1aNAJXItCTLUsnz8BEuGGnIMOTP983sCdMEcmCFVc24gNARQJLmh8fhDLio159kXuRB3kWS-2B8z2pdvCdbFf6FZGF0CQzzi-2FPGtNZ6HsHWSV-2FuZyFMP6TXdBXepRg-3D-3DM7v__U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyotOYWK-2F0IFHnWW-2BRBfGKdwZNqAt0U4-2BsiV4Ztdrg14up3peDJDkBFqvYgNwnNOT5chwXLBKjGjzm6HPVYPJw6SMprU2llFVqzJ2R80mMF5C7A9hv9LGX85vlEyI-2BSCz2aEoFjCFX3A1i2-2Ba-2FYi7MzMAoair0b-2F6xbbgbVX5qH4wEQ-3D-3D
> >
> > .
> > You are receiving this because you are subscribed to this thread.Message
> > ID: ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38EV0gzJRrfk3hb1n3baLjnAps2YoKFnKIRJWm7CYkRcJLeM5-2BzMZxh5o7QjlzPCbLJzwwW0-2Bs8D6JlE6wwq7X3ZuOTPJ7M7EouyQ-2Fx3NomYXCd0T_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyotOYWK-2F0IFHnWW-2BRBfGKdwZUc-2BcnB5ooJK-2FjAlVVADtRbA8t-2FWjL2-2Fqk1jaWZ4nHd9x-2BA7faOaQjwmD8nfFg-2F2rSelGkVMj86-2B0z26SCvL8CKAuyh-2BqaBcCl-2FP01miIVa-2F-2B7YjrG7CtJ-2Fq0y8G6BCCx-2FlhJlceXpYf1TLDc-2FA909Q-3D-3D>,
> or unsubscribe
> <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38OLpao1aNAJXItCTLUsnz8BEuGGnIMOTP983sCdMEcmCSlM-2BfHgNDr6WOGQnhRZgDPhT-2BPyCnoN-2BI4tO94T6r6h6RSVB8av1TgL-2F1HeSn1g4iBedqZcEd5dclrN2R5yInQ-3D-3DMpef_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyotOYWK-2F0IFHnWW-2BRBfGKdwZ1WNgM4OV-2FdVUuoAqYzU3-2Fubga7QKZW7KKx1mgEDSihxKvWccDdYLkZK1OkQ2vSbOTJ4-2FNN4FAdHc0m3sdcnhZIiwxjxR9BumyybWuGf5iKVoXm-2FSF58qJmFzQJUqhj-2BHox2agQeNmnKKI-2B87EdPUVw-3D-3D>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

-- 
NOTICE: The information contained in this transmission and any
attachments 
is confidential and is for the use of the intended recipient(s)
only. If 
you have received in error, please notify the sender and delete it. If
you 
are not the intended recipient, you must not use, disclose or distribute
this e-mail without the author's prior permission.

**Comment by Ranjit-Chigurupati** [comment]
+ HR.

You should understand what "Intellectual Property'' is and Do's and Dont's.
You had violated the organization policy by uploading the Highradius
Intellectual property over the internet. It is our "Intellectual Property''
whether it is demo, training or prod, etc. And no one has authorisation to
use it outside of an organization.

Wherever you're working - adhere to organization compliance policies to
avoid legal consequences.

Please delete the repository and update the status.

On Mon, Oct 3, 2022 at 11:11 AM Ranjit Kumar Chigurupati <
***@***.***> wrote:

> +Naresh Goud ***@***.***>
>
> On Fri, Sep 30, 2022 at 4:50 PM Abhishek Vardhan ***@***.***>
> wrote:
>
>> Hi there,
>> Can you please mention the exact details of the source code which belongs
>> to highradius .It was actually a web project that every tech intern had to
>> do and and I didn’t use any highradius framework in the project . If any i
>> would be happy to rectify or remove ,please mention the source code
>> details.
>>
>> Thank you.
>> Abhishek Vardhan
>>
>> On Fri, 30 Sep 2022 at 12:33 PM, Ranjit-Chigurupati <
>> ***@***.***> wrote:
>>
>> > Hi abhishek000yadav,
>> >
>> > We identified that one of your GitHub public Repositories “HighRadius1”
>> > contains a source code which is related/owned by the Highradius. Please
>> > Delete/remove the respective data from the public exposure, if not this
>> > will be considered as a Copyright Violation and necessary action will be
>> > taken.
>> >
>> > Any data that is related/owned by the Highradius Corporation should not
>> be
>> > used for your personal benefits or should not exposed in to the public.
>> Any
>> > such unauthorized activities will be considered as series offence and
>> > necessary legal actions will be taken.
>> >
>> > Thanks & Regards,
>> > Ranjit Kumar Chigurupati,
>> > Led Information Security Engineer,
>> > Highradius Corporation.
>> >
>> > —
>> > Reply to this email directly, view it on GitHub
>> > <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38EV0gzJRrfk3hb1n3baLjnAps2YoKFnKIRJWm7CYkRcJLeM5-2BzMZxh5o7QjlzPCbLH0c6SrKThVH61uLpj1UUTY-3DB8a7_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyoujY7nokwlAOcQSHKyUmc3G4QxeXpQhl9w0N5a-2Bn1g3qLFoVNVvakZJSeLryje-2Fb6-2BIfV7sCm7aZH5Rtp4toQOKhrm96wvtzk-2FVxd5mB2LpYBaZDSMsUUPVB7EjpB0cpxGu1sxY3hoORL-2FqvsGP3Bnsv6bsxQ3FtdebCJ8nXZmyWQ-3D-3D>, or
>> unsubscribe
>> > <
>> https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38OLpao1aNAJXItCTLUsnz8BEuGGnIMOTP983sCdMEcmCFVc24gNARQJLmh8fhDLio159kXuRB3kWS-2B8z2pdvCdbFf6FZGF0CQzzi-2FPGtNZ6HsHWSV-2FuZyFMP6TXdBXepRg-3D-3DxbSM_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyoujY7nokwlAOcQSHKyUmc3G7xJnfeSq1CFaT7l2tXOAkudsuPpxaxo2sxWMsqNB3Xmdyq-2BsKcV3oW4mt0k9bNoCmYVEIkxWrC57W2Qxpd7tiRBw1fMh8Yan8kkNaBONRZvsKNNeIEQOo8-2F9CJPBB5I9QCiisw0P0L1YKRT8RDg38w-3D-3D
>> >
>> > .
>> > You are receiving this because you are subscribed to this thread.Message
>> > ID: ***@***.***>
>> >
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38EV0gzJRrfk3hb1n3baLjnAps2YoKFnKIRJWm7CYkRcJLeM5-2BzMZxh5o7QjlzPCbLJzwwW0-2Bs8D6JlE6wwq7X3ZuOTPJ7M7EouyQ-2Fx3NomYXF7ra_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyoujY7nokwlAOcQSHKyUmc3GdD4Zk71cI4jsLLio3W-2FvGvGH-2BOk9tucHUqLeZ9ENc9ro83WHCKV0cEOkjjmvnjEqEpBV8XRFsph9HUnDFx4wLXvM8EYYWsKpv99gLbDTYzTW3ucFL9vhoF3YaYKdx63VHkohX9izirL4Vy8SeSbq2A-3D-3D>,
>> or unsubscribe
>> <https://u27439339.ct.sendgrid.net/ls/click?upn=mE3tPWHeQaDGIP2OtX-2F38OLpao1aNAJXItCTLUsnz8BEuGGnIMOTP983sCdMEcmCSlM-2BfHgNDr6WOGQnhRZgDPhT-2BPyCnoN-2BI4tO94T6r6h6RSVB8av1TgL-2F1HeSn1g4iBedqZcEd5dclrN2R5yInQ-3D-3DVnC5_U31jt5HgHBh7k3Grc5s4lyh4Ci3wafEo74MqQptFI-2Bf9N7cA3TNXXIFUznpuqWr6Belw7jRdSr3YVKCu3NhE2QOXs2JU38V5YHCbY6GPyoujY7nokwlAOcQSHKyUmc3G-2BjQSqm5bxtZNKGfp2g5q8-2BQXDFq8K9MpLhR8uWqWOWk-2F7-2B7ZbB0jXhXzT21xWFI-2BDkzKsV00OGU8xAtd2lMK01WVYTTlLfapUZFp9PggG5dk7DRU9EJCfu-2B2JzlmF6xN3zsV0D-2BAPRpRRC3DeSOLvg-3D-3D>
>> .
>> You are receiving this because you authored the thread.Message ID:
>> ***@***.***>
>>
>

-- 
Regards,
Naresh.

-- 
NOTICE: The information contained in this transmission and any
attachments 
is confidential and is for the use of the intended recipient(s)
only. If 
you have received in error, please notify the sender and delete it. If
you 
are not the intended recipient, you must not use, disclose or distribute
this e-mail without the author's prior permission.

**Comment by abhishek000yadav** [comment]
Hi Ranjit,

I have deleted all the related source code from the repository .Have a look ,if there is any other change i need to do.
